switch moduleResolution to "node" to avoid TS error
 error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.