chore(deps-dev): bump typescript from 4.5.2 to 5.2.2 (#89)
Also switch "moduleResolution" to "node" in the tsconfig file of the `addons` package to avoid TS error:
    error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Thomas Bouffard <27200110+tbouffard@users.noreply.github.com>